name: "{{NAME}}-{{TYPE}}"

on:
  push:
    paths:
      - "service/{{NAME}}/{{TYPE}}/**"
      - ".github/workflows/{{NAME}}.yaml"

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Run tests
  #       run: |-
  #         cd routes/{{NAME}}
  #         go test ./...
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out code

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: build & push to DockerHub
      with:
        image: dfang/mall-{{NAME}}-{{TYPE}}
        # tags: ${{ github.sha }}, ${{ steps.docker_meta.outputs.tags }}, latest
        tags: latest, ${{ github.sha }}
        registry: docker.io
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        dockerfile: service/{{NAME}}/{{TYPE}}/Dockerfile
        directory: service/{{NAME}}/{{TYPE}}

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: build & push to ghcr.io
      with:
        image: dfang/mall-{{NAME}}-{{TYPE}}
        tags: latest, ${{ github.sha }}
        registry: ghcr.io
        username: dfang
        password: ${{ secrets.GHCR_TOKEN }}
        dockerfile: service/{{NAME}}/{{TYPE}}/Dockerfile
        directory: service/{{NAME}}/{{TYPE}}

