Name: product.rpc
ListenOn: 127.0.0.1:9001
Log:
  Level: info

Etcd:
  Hosts:
    - etcd:2379
  Key: product.rpc

DataSource: root:root@tcp(mysql:3306)/mall?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

Cache:
  - Host: redis:6379
    Type: node # node可以不写，可以设为cluster
    # Pass: xxx # 如果有密码
